pull_request_rules:
  - name: automatic merge successful scala-steward PRs
    conditions:
      - author=scala-steward
      - "#status-failure=0"
    actions:
      merge:
        method: merge
        strict: true
